[package]
name = "indexer-alt-object-store"
version.workspace = true
license = "Apache-2.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
indexer-store-traits.workspace = true
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
indexer-store-traits = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
