name: Bug Report
description: Report a bug in SOMA
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the details below so we can investigate.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SOMA Version
      description: Output of `soma --version` or SDK version
      placeholder: "e.g., 0.1.0"
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: "e.g., Ubuntu 22.04, macOS 15, Windows 11"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps or code to reproduce the issue
      placeholder: |
        1. Run `soma ...`
        2. Observe ...
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error messages or logs
      render: shell
