Orchestrator

ObjectStorageActor
EmbeddingModelActor
CompressionActor


Orchestrator <-> ObjectStorageActor: Step 1
Orchestrator <-> EmbeddingModelActor: Step 2
Orchestrator <-> CompressionActor: Step 3