Service {
    HandleInput
    HandleCommit
    HandleReveal
}

Pipelines {
    ProcessInput
    ProcessCommit
    ProcessReveal
}

Workers {
    DownloadActor
    EmbeddingModelActor
    CompressionActor
    EncryptionActor
}

Service.HandleInput -> Pipelines.ProcessInput
Service.HandleCommit -> Pipelines.ProcessCommit
Service.HandleReveal -> Pipelines.ProcessReveal


Pipelines.ProcessInput -> Workers.DownloadActor
Pipelines.ProcessInput -> Workers.EmbeddingModelActor
Pipelines.ProcessInput -> Workers.CompressionActor
Pipelines.ProcessInput -> Workers.EncryptionActor


Pipelines.ProcessCommit -> Workers.DownloadActor

Pipelines.ProcessReveal -> Workers.CompressionActor
Pipelines.ProcessReveal -> Workers.EncryptionActor